<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoWarn>CA1050;CA1822</NoWarn>
    <UserSecretsId>ae9edd28-3e89-4f3a-b971-b7cc56befaad</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Humanizer" Version="2.14.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.52.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
    <PackageReference Include="Spectre.Console.Json" Version="0.50.0" />
    <PackageReference Include="Stubble.Compilation" Version="1.10.8" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../reference/**/*.yml">
      <LogicalName>utilities.reference.$([System.String]::Copy('%(RecursiveDir)%(Filename)%(Extension)').Replace('/','.').Replace('\','.'))</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="../templates/reference.mustache.tmpl">
      <LogicalName>utilities.templates.reference.mustache.tmpl</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="../templates/landing.mustache.tmpl">
      <LogicalName>utilities.templates.landing.mustache.tmpl</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
