services:
  dev:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    command: sleep infinity
    volumes:
      - ..:/workspace
    depends_on:
      - cosmosdb
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    hostname: cosmosdb.domain
    ports:
      - 8081
      - 1234