services:
  dev:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    command: sleep infinity
    volumes:
      - ..:/workspace
    environment:
      COSMOSDB_CONNECTIONSTRING: "AccountEndpoint=https://cosmosdb:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
    depends_on:
      - cosmosdb
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    environment:
      PROTOCOL: "https"
      ENABLE_EXPLORER: "false"
      GATEWAY_PUBLIC_ENDPOINT: "cosmosdb"
    ports:
      - 8081