name: Validate query samples
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate:
    name: Validate query samples
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:9.0
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081
          - 1234:1234
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        working-directory: ./tests/unit/
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        env:
          COSMOSDB__CONNECTIONSTRING: "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tests/unit/TestResults/**/*.trx
          