name: Validate query samples
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate:
    name: Validate query samples
    runs-on: ubuntu-latest
    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081
          - 1234:1234 
          - 10250-10255:10250-10255
        env:
          PROTOCOL: https
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Run unit tests
        working-directory: ./tests/unit/
        run: dotnet test --logger "console" --logger "trx;verbosity=detailed"
        env:
          PROTOCOL: "https"
          ENABLE_EXPLORER: "false"
          COSMOSDB_CONNECTIONSTRING: "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: /tests/unit/TestResults/**/*.trx
          